services:
  postgres:
    image: postgres:16.6-alpine3.21
    container_name: postgres-terapi
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: miusuario
      POSTGRES_PASSWORD: mipassword
      POSTGRES_DB: db_terapi
    volumes:
      - ./datos:/var/lib/postgresql/data